name: pocketbase

# docker network create web
networks:
  default:
    name: web
    external: true

services:

  pocketbase:
    build:
      context: ./
    restart: unless-stopped
    container_name: pocketbase
    deploy:
      resources:
        limits:
          cpus: 0.8 # 80% des 2 vCPU
          memory: 4G
        reservations:
          cpus: 0.2  # RÃ©server au minimum 20% des CPU
          memory: 2G
    ports:
      - "8090:8090"
    environment:
      DENO_ENV: production
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - ./jobs:/app/jobs
      - ../common:/app/common
      - ./pb_data:/app/pb_data
      - ./pb_hooks:/app/pb_hooks
      - ./pb_migrations:/app/pb_migrations
      - ./pb_public:/app/pb_public
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://0.0.0.0:8090/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
